---
apiVersion: v1
kind: Service
metadata:
  name: {{ (printf "%s-%s" .Release.Name .Chart.Name ) | quote }}
  labels:
{{ include "mergeLabels" . | nindent 4 }}
  annotations:
{{ include "mergeAnnotations" . | nindent 4 }}
{{- with .Values.service.annotations }}
{{ toYaml . | nindent 4 }}
{{- end }}
spec:
{{ toYaml .Values.service.spec | indent 2 }}
  selector:
    app: {{ include "fullname" . }}
