
{{- range $sc := .Values.storage.mounts }}
{{- if $sc.enabled -}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ (printf "%s-%s" (include "fullname" $) $sc.name) }}
  labels:
{{- include "mergeLabels" $ | nindent 4 }}
  annotations:
{{- include "mergeAnnotations" $ | nindent 4 }}
spec:
  storageClassName: {{ $sc.storageClass }}
  accessModes:
    - {{ $sc.accessMode | quote }}
  resources:
    requests:
      storage: {{ $sc.size | quote }}

{{- end -}}
{{- end -}}
