{{- $dataVol := .Values.storage.data }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ (printf "%s-%s" .Release.Name .Chart.Name ) | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "fullname" . }}
    spec:
      volumes:
        {{- if $dataVol.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ $dataVol.existingClaim | default (printf "%s-%s-data" .Release.Name .Chart.Name) }}
          {{- else }}
          emptyDir: {}
        {{- end }}
        {{- if .Values.storage.extraVolumes }}
          {{- .Values.storage.extraVolumes | toYaml | nindent 8}}
        {{- end }}

      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            {{- if $dataVol.enabled }}
            - name: data
              mountPath: {{ $dataVol.path }}
            {{- end }}
            {{- if .Values.storage.extraMounts }}
            {{- .Values.storage.extraVolumes | toYaml | nindent 12}}
            {{- end }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "secretName" . | quote }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "secretName" . | quote }}
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "secretName" . | quote }}
                  key: POSTGRES_DB

