{{ if not .Values.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secretName" . | quote }}
type: Opaque
data:
  POSTGRES_DB: {{ .Values.secret.POSTGRES_DB | b64enc | quote }}
  POSTGRES_USER: {{ .Values.secret.POSTGRES_USER | b64enc | quote }}
  POSTGRES_PASSWORD: {{ include "randomPassword" . | b64enc | quote }}
{{- end }}
