{{ if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . | quote }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: {{ include "fullname" . | quote }}
{{ end }}

