apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname_postgres" . | quote }}
  labels:
{{- $labels := fromYaml (include "mergeLabels" .) }}
{{- $_ := set $labels "app" (include "fullname_postgres" .) }}
{{ toYaml $labels | nindent 4 }}
spec:
  replicas: {{ .Values.postgres.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "fullname_postgres" . }}
  template:
    metadata:
      labels:
{{- $labels := fromYaml (include "mergePodLabels" .) }}
{{- $_ := set $labels "app" (include "fullname_postgres" .) }}
{{ toYaml $labels | nindent 8 }}
    spec:
      {{- if .Values.postgres.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.postgres.imagePullSecrets | indent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.postgres.serviceAccountName | default "" }}
      securityContext:
{{- toYaml .Values.podSecurityContext | nindent 8 }}
      affinity:
{{- toYaml .Values.postgres.affinity | nindent 8 }}
      nodeSelector:
{{- toYaml .Values.postgres.nodeSelector | nindent 8 }}
      tolerations:
{{- toYaml .Values.postgres.tolerations | nindent 8 }}
      containers:
        - name: postgres
          image: {{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.postgres.service.port }}
          resources:
{{ toYaml .Values.postgres.resources | nindent 12 }}
          securityContext:
{{- toYaml .Values.postgres.securityContext | nindent 12 }}
          livenessProbe:
{{- if .Values.postgres.livenessProbe }}
{{ toYaml .Values.postgres.livenessProbe | nindent 12 }}
{{- end }}
          readinessProbe:
{{- if .Values.postgres.readinessProbe }}
{{ toYaml .Values.postgres.readinessProbe | nindent 12 }}
{{- end }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.postgres.storage.data.path }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "secretName" . }}
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "secretName" . }}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "secretName" . }}
                  key: POSTGRES_PASSWORD
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ printf "%s-data" (include "fullname_postgres" .) | quote }}
