
name: "postgres"
image:
  repository: postgres
  tag: "18.1"
secret:
  # You can either provide an already existing secret, OR you can let the
  # secret be created automtically
  existingSecret: ""  
  name: ""               # Only used if the existingSecret is not given
  POSTGRES_DB: "user"    # The name of the database to create
  POSTGRES_USER: "user"  
  POSTGRES_PASSWORD: ""      # A random password will be generated if not given
storage:
  data:
    enabled: true
    existingClaim: "" 
    storageClass: ""
    accessMode: ReadWriteOnce
    path: "/var/lib/postgresql"
    size: 2Gi
  extraVolumes:  []
#   - name: myvolume
#     emptyDir: {}
  extraMounts: []
service:
  enabled: true
  type: ClusterIP
  port: 5432
